version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-taskboard
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    restart: always
