version: "3"
services:

  app:
    build:
      context: https://github.com/airbornelamb/docker-taskboard
      dockerfile: Dockerfile
    image: docker-taskboard
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
